### ISSUE TITLE
Plugin Restarting

### ISSUE THREAD

**Issue by Shikhar1212** [sjlu/homebridge-mila#2]
Hello, im running this on a Mac, do you think based on the log below, that is why im having issues running this plugin? It is restarting on its own. Thank you very much for your help.

[8/10/2023, 9:11:53 PM] [homebridge-mila] Launched child bridge with PID 61778
[8/10/2023, 9:11:53 PM] Registering platform 'homebridge-mila.Mila'
[8/10/2023, 9:11:54 PM] [homebridge-mila] Loaded homebridge-mila v1.2.3 child bridge successfully
[8/10/2023, 9:11:54 PM] Homebridge v1.6.1 (HAP v0.11.1) (homebridge-mila) is running on port 58287.

/usr/local/lib/node_modules/homebridge-mila/node_modules/lodash/lodash.js:3032
      return object && baseFor(object, iteratee, keys);
                       ^
TypeError: Cannot read properties of null (reading 'value')
    at /usr/local/lib/node_modules/homebridge-mila/lib/mila-client.js:225:27
    at /usr/local/lib/node_modules/homebridge-mila/node_modules/lodash/lodash.js:13469:38
    at /usr/local/lib/node_modules/homebridge-mila/node_modules/lodash/lodash.js:4967:15
    at baseForOwn (/usr/local/lib/node_modules/homebridge-mila/node_modules/lodash/lodash.js:3032:24)
    at Function.mapValues (/usr/local/lib/node_modules/homebridge-mila/node_modules/lodash/lodash.js:13468:7)
    at /usr/local/lib/node_modules/homebridge-mila/node_modules/lodash/lodash.js:4430:28
    at arrayReduce (/usr/local/lib/node_modules/homebridge-mila/node_modules/lodash/lodash.js:697:21)
    at baseWrapperValue (/usr/local/lib/node_modules/homebridge-mila/node_modules/lodash/lodash.js:4429:14)
    at LodashWrapper.wrapperValue (/usr/local/lib/node_modules/homebridge-mila/node_modules/lodash/lodash.js:9114:14)
    at /usr/local/lib/node_modules/homebridge-mila/lib/mila-client.js:227:10
    at arrayMap (/usr/local/lib/node_modules/homebridge-mila/node_modules/lodash/lodash.js:653:23)
    at Function.map (/usr/local/lib/node_modules/homebridge-mila/node_modules/lodash/lodash.js:9622:14)
    at MilaClient.getAppliances (/usr/local/lib/node_modules/homebridge-mila/lib/mila-client.js:221:26)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at MilaHomebridgePlatform.discoverDevices (/usr/local/lib/node_modules/homebridge-mila/src/platform.ts:56:24)
[8/10/2023, 9:11:54 PM] [homebridge-mila] Child bridge process ended
[8/10/2023, 9:11:54 PM] [homebridge-mila] Process Ended. Code: 1, Signal: null

**Comment by sjlu** [comment]
What version of Node are you running?

**Comment by Shikhar1212** [comment]
v18.17.0

Thank you!
